export const SET_ALL_PATIENTS = "SET_ALL_PATIENTS"
export const RESET_ALL_PATIENT = "RESET_ALL_PATIENT"

export const GET_PATIENT_DETAILS = "GET_PATIENT_DETAILS"
export const SET_PATIENT_DETAILS = "SET_PATIENT_DETAILS"
export const SET_PATIENT_ID = "SET_PATIENT_ID"
export const PATIENT_SAVED = "PATIENT_SAVED"
export const RESET_INITIAL_STATE = "RESET_INITIAL_STATE"

export const GET_PATIENT_SEARCHBOX = "GET_PATIENT_SEARCHBOX"
export const SET_PATIENT_SEARCHBOX = "SET_PATIENT_SEARCHBOX"
export const TOGGLE_SEARCHBOX = "TOGGLE_SEARCHBOX"
export const TOGGLE_LOADING = "TOGGLE_LOADING"


